FROM python:3.6

RUN apt-get update && apt-get install -y \
    build-essential \
    libssl-dev \
    supervisor \
    curl \
    nginx \
    python-dev \
    git &&\
    apt-get -q clean -y && rm -rf /var/lib/apt/lists/* && rm -f /var/cache/apt/*.bin

RUN python -m venv .env
RUN . .env/bin/activate

RUN git clone https://github.com/explosion/spaCy
WORKDIR /spaCy
RUN git fetch --tags && git checkout v2.1.0
RUN pip install -r requirements.txt
RUN python setup.py build_ext --inplace
RUN python setup.py install

RUN python -m spacy download en_core_web_sm

WORKDIR /
RUN git clone https://github.com/huggingface/neuralcoref.git
WORKDIR /neuralcoref
# RUN python -m spacy validate
RUN pip install -r requirements.txt
# RUN pip install -e .

RUN python setup.py build_ext --inplace
RUN python setup.py install

ENV NEURALCOREF_CACHE=/neuralcoref-cache
RUN mkdir /neuralcoref-cache
RUN (cd /neuralcoref-cache && curl -O https://s3.amazonaws.com/models.huggingface.co/neuralcoref/neuralcoref.tar.gz) &&\
  mv /neuralcoref-cache/neuralcoref.tar.gz /neuralcoref-cache/f46bc05a4bfba2ae0d11ffd41c4777683fa78ed357dc04a23c67137abf675e14.7d6f9a6fecf5cf09e74b65f85c7d6896b21decadb2554d486474f63b95ec4633

WORKDIR /
RUN git clone https://github.com/NervanaSystems/nlp-architect
WORKDIR /nlp-architect
RUN python setup.py build_ext --inplace
RUN python setup.py install
ENV NLP_ARCHITECT_BE=CPU

WORKDIR /root

CMD python

