FROM python:3.6

RUN apt-get update && apt-get install -y \
    build-essential \
    libssl-dev \
    supervisor \
    curl \
    nginx \
    python-dev \
    git &&\
    apt-get -q clean -y && rm -rf /var/lib/apt/lists/* && rm -f /var/cache/apt/*.bin

RUN pip install spacy==2.1.0

RUN python -m spacy download en_core_web_sm
RUN python -m spacy link en_core_web_sm en

# not sure on how much more benefit is gained from using the larger model:
# RUN python -m spacy download en_core_web_md
# RUN python -m spacy link en_core_web_md en

RUN pip install neuralcoref

ENV NEURALCOREF_CACHE=/neuralcoref-cache
RUN mkdir /neuralcoref-cache
RUN (cd /neuralcoref-cache && curl -O https://s3.amazonaws.com/models.huggingface.co/neuralcoref/neuralcoref.tar.gz) &&\
  mv /neuralcoref-cache/neuralcoref.tar.gz /neuralcoref-cache/f46bc05a4bfba2ae0d11ffd41c4777683fa78ed357dc04a23c67137abf675e14.7d6f9a6fecf5cf09e74b65f85c7d6896b21decadb2554d486474f63b95ec4633 &&\
  cd

WORKDIR /

COPY ./requirements.txt /
RUN pip install -r requirements.txt

# ENV NLP_ARCHITECT_BE=CPU
# RUN pip install nlp-architect

# numpy==1.16.3
RUN pip install torch==1.0.1
RUN pip install transformers==2.0.0
RUN pip install Cython==0.29.10
RUN pip install tqdm==4.32.2
# neuralcoref==4.0
RUN pip install argparse
RUN pip install scikit-learn
RUN pip install beautifulsoup4
RUN pip install lxml

RUN mkdir /bert-model
WORKDIR /bert-model
# https://github.com/huggingface/transformers/issues/451
# https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-vocab.txt
# https://s3.amazonaws.com/models.huggingface.co/bert/distilbert-base-uncased-config.json
# https://s3.amazonaws.com/models.huggingface.co/bert/distilbert-base-uncased-pytorch_model.bin
# # just pytorch file needed:
# # https://s3.amazonaws.com/models.huggingface.co/bert/distilbert-base-uncased-tf_model.h5

RUN wget -O pytorch_model.bin https://s3.amazonaws.com/models.huggingface.co/bert/distilbert-base-uncased-pytorch_model.bin
RUN wget -O config.json https://s3.amazonaws.com/models.huggingface.co/bert/distilbert-base-uncased-config.json
RUN wget -O vocab.txt https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-vocab.txt

# RUN pip install bert-extractive-summarizer==0.2.0
ARG CACHEBUST=1

WORKDIR /
RUN git clone https://github.com/joshweir/bert-extractive-summarizer
# RUN python -m venv .env
# RUN . .env/bin/activate
WORKDIR /bert-extractive-summarizer
# RUN git fetch origin more-options && git checkout more-options
RUN pip install -r requirements.txt
RUN python setup.py build_ext --inplace
RUN python setup.py install

ADD ./ /app

WORKDIR /app

# CMD gunicorn --bind 0.0.0.0:80 \
#   --worker-tmp-dir /dev/shm \
#   --workers=1 --threads=4 --worker-class=gthread \
#   --log-file=- \
#   --preload \
#   wsgi:app
CMD python server.py
